# Generated by Django 5.0.7 on 2024-07-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Cus_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Cus_Number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='Sup_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='Sup_Number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
