# Generated by Django 5.0.7 on 2024-07-16 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customers_created_alter_customers_cus_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='Sale',
        ),
        migrations.AddField(
            model_name='saledetails',
            name='Sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sales'),
        ),
    ]
