# Generated by Django 5.0.7 on 2024-07-16 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sales_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.purchase'),
        ),
    ]
