# Generated by Django 5.0.7 on 2024-07-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_purchase_product_remove_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='costPrice',
            field=models.IntegerField(default=0),
        ),
    ]
