# Generated by Django 5.0.7 on 2024-07-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_products_costprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
    ]
