# Generated by Django 5.0.7 on 2024-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='Cus_Purchase',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
