# Generated by Django 5.0.7 on 2024-07-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_expense_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expensedetails',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
