# Generated by Django 5.0.7 on 2024-08-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_expensedetails_quantity_expensedetails_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='saledetails',
            name='Rate',
            field=models.IntegerField(default=1),
        ),
    ]
