# Generated by Django 5.0.7 on 2024-08-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_saledetails_name_saledetails_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetails',
            name='Name',
        ),
    ]
