# Generated by Django 5.0.7 on 2024-08-02 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_saledetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='pur_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='Sup_Purchase',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
