# Generated by Django 5.0.7 on 2024-08-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_purchase_pur_date_sales_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['pur_date']},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['sale_date']},
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='Rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='Rate',
            field=models.IntegerField(default=0),
        ),
    ]
