# Generated by Django 5.0.7 on 2024-08-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_purchase_options_alter_sales_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='sellRate',
            field=models.IntegerField(default=0),
        ),
    ]
