# Generated by Django 5.0.7 on 2024-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_customers_cus_purchase_alter_expense_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Cus_Number',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='Sup_Number',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
